### ISSUE TITLE
[Front Page] Design changes as requested by the client

### ISSUE THREAD

**Issue by jdesiloniz** [47deg/scala-lang#24]
These design changes were requested by the client and we agreed to tackle them:

* Bold fonts should be heavier throughout the website.
* The "Getting started" link should be highlighted more than now (I don't know if by increasing font size or making a border around it).
* Add tooltip to the Scala IDEs section, for those that have ensime support.
* Create a separate section for scastie ("Scala in the browser") when they've got content for it.
* Blog tags in the preview articles list should be bolder (both the "BLOG" title under What's new and the little red tags at the sides of each post; those should be bolder and larger).
* Scala Center supporter icons should be retina-ready.
* Scala icon at the footer should be retina-ready.
* Add text (under the Scala version) like: "Scala compiles to JVM and Javascript"

**Comment by jdesiloniz** [comment]
@israelperezglez these changes are to be done together with #23

**Comment by israelperezglez** [comment]
- [x] Bold fonts should be heavier throughout the website.
- [x] The "Getting started" link should be highlighted more than now (I don't know if by increasing font size or making a border around it).
- [x] Add text (under the Scala version) like: "Scala compiles to JVM and Javascript"
- [ ] Add tooltip to the Scala IDEs section, for those that have ensime support
- [ ] Create a separate section for scastie ("Scala in the browser") when they've got content for it.
- [x] Blog tags in the preview articles list should be bolder (both the "BLOG" title under What's new and the little red tags at the sides of each post; those should be bolder and larger).
- [ ] Scala Center supporter icons should be retina-ready.
- [x] Scala icon at the footer should be retina-ready.

**Comment by jdesiloniz** [comment]
These were checked and implemented in the actual layouts as part of work reflected in https://github.com/47deg/scala-lang/pull/26
