### ISSUE TITLE
Setting up PR to scala-lang repo

### ISSUE THREAD

**Issue by dominv** [47deg/scala-lang#52]
This Issue involves the following tasks:

 - [x] Setting up the PHP scripts to work with the new website's version. (Already allocated in the scala-lang_private repository. 
 - [x] Updating our master branch with the latest changes from scala-lang master branch. 
 - [x] Launch the PR from our master branch to scala-lang repository master branch.

**Comment by dominv** [comment]
The Scala Lang PR has already been merged and the site is live now! For what I've seen so far everything is working fine

**Comment by SethTisue** [comment]
@dominv 🎉, congrats & thanks for your excellent work on this

**Comment by dominv** [comment]
@SethTisue Thanks a lot!!!
