### ISSUE TITLE
Fix EPFL marker's position

### ISSUE THREAD

**Issue by dominv** [47deg/scala-lang#54]
Fix EPFL marker's position on the front page

**Comment by dominv** [comment]
QA Tasks: 

- Go to the deployed app in https://scala-lang-site-pr-53.herokuapp.com/
- Check in the front page that, the EPFL marker is its correct location. 
- Check that for different window's sizes the marker goes to its correct position again. 

@jorgegalindocruces could you please review?

Thanks!

**Comment by dominv** [comment]
@anamariamv could you please review this issue? 

Thanks!

**Comment by anamariamv** [comment]
LGTM!!
